### ISSUE TITLE
[Task]: Add Shimmer Python Code Examples

### ISSUE THREAD

**Issue by lucas-tortora** [iotaledger-archive/iota.rs#1387]
### Task description

As we aim to make developer onboarding easy in all languages, it'd be great to provide the same examples in all languages.  

### Requirements

Add examples showcasing the following functionalities using the Python binding:

- [x] Get a raw block
- [x] Build an NFT output
- [x] Build a Foundry output
- [x] Build and Alias Output

### Acceptance criteria

- [ ] The examples have been added to the binding 
- [ ] The examples have been added to the doc's how-to guides

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
