### ISSUE TITLE
[Task]: Add compute alias/nft/foundry id to bindings

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#1417]
### Task description

Add ComputeAliasId, ComputeNftId, ComputeFoundryId to bindings
- [ ] nodejs binding
- [ ] python binding

### Requirements

-

### Acceptance criteria

-

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
