### ISSUE TITLE
[Task]: Add nftIdToBech32 to message interface and bindings

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#1430]
### Task description

Similar to aliasIdToBech32 here https://github.com/iotaledger/iota.rs/pull/1428/files just for an NFT id

### Requirements

Added to:
- [x] message interface
- [x] java
- [x] python
- [x] nodejs

### Acceptance criteria

-

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
