### ISSUE TITLE
[Task]: Tracking issue for Github Actions workflow refreshment and test improvements

### ISSUE THREAD

**Issue by jyhi** [iotaledger-archive/iota.rs#782]
This is a tracking issue for refurbishing our CI automation workflows and gradually improving the coverage of testing / automation tasks they run.

There are several reasons for splitting the whole task:

1. Initial researches have revealed multiple problems in both of the current workflows and the tests we wrote some time ago.
2. There has been a few pending proposal for improving the workflow; this refurbishment should include them too:
    1. #661
        1. #680
    2. #727
3. We want to also learn from other teams (e.g. identity, streams) on how to organize the workflows better.
4. We want to make them as [reusable](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows) as possible.

Directly merging all the changes would cause too many failures, affecting the PR reviewing process. Thus, multiple changes will be PR-ed into the repository one-by-one.

This is a relatively huge damage so it's hard to list every change that would be made - but every PR should be listed here until all tests are enabled and passed.

## Tasks

- [x] Switch the Node.js build system to yarn (#784)
- [x] **PR new workflows, but with failing tests disabled** (#785)
- [x] Fix obsolete assertions in tests of the Node.js bindings (#792)
- [x] Fix Clippy warnings in the Rust core (#793)
- [x] Fix Clippy warnings in the Java bindings (#794)
- [x] Fix Clippy warnings in the Node.js bindings
- [x] Fix Clippy warnings in the Python bindings (#796)
- [x] Fix Clippy warnings in the WebAssembly bindings (#797)
- [x] Fix security auditing problems (#795)
