### ISSUE TITLE
[Task]: Update ledger signer to stardust

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#873]
### Task description

Update ledger signer to stardust (ledger nano app needs to be updated first with trusted mode(signing only essence))

### Requirements

- [x] Generate addresses with different coin types
- [x] Sign transactions

### Acceptance criteria

Address generation with IOTA and SHIMMER coin type is working
transaction signing is working

### Creation checklist

- [x] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project
