### ISSUE TITLE
[Task]: Docs - Versioning Updates

### ISSUE THREAD

**Issue by charlesthompson3** [iotaledger-archive/iota.rs#876]
### Task description

With the upcoming stardust changes, some articles in the documentation may require updates and versioning.

And we need to be able to launch products with their respective docs to improve the overall developer experience.

### Requirements

The following pages may require updating. Please feel free to add or remove any items you see fit.

- [ ] Overview
  - [ ] Rust
    - [ ] Getting started
      - [ ] How to setup?
      - [ ] Examples
    - [ ] Guides
      -  [ ] Guide X
    - [ ] API Reference
  - [ ] Node.js
    - [ ] Getting started
      - [ ] How to setup?
      - [ ] Examples
    - [ ] Guides
      -  [ ] Guide X
    - [ ] API Reference
  - [ ] Java
    - [ ] Getting started
      - [ ] How to setup?
      - [ ] Examples
    - [ ] Guides
      -  [ ] Guide X
    - [ ] API Reference
  - [ ] Python
    - [ ] Getting started
      - [ ] How to setup?
      - [ ] Examples
    - [ ] Guides
      -  [ ] Guide X
    - [ ] API Reference
- [ ] Troubleshooting
- [ ] Contribute

### Acceptance criteria

To the extent I can, I will try to accomplish these updates via a PR, but the @iotaledger/tech-writers team will require support from the developers to know exactly what should be updated.

The parent issue link can be found here:  https://github.com/iotaledger/stardust-project/issues/45

### Creation checklist

- [ ] I have assigned this task to the correct people
- [ ] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by thibault-martinez** [comment]
@iotaledger/tech-writers What's the status on this please ?

**Comment by thibault-martinez** [comment]
Closed for https://github.com/iotaledger/iota.rs/issues/1098, https://github.com/iotaledger/iota.rs/issues/1099, https://github.com/iotaledger/iota.rs/issues/1100 and https://github.com/iotaledger/iota.rs/issues/1101
