### ISSUE TITLE
[Task]: Make remaining function available via the message interface

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#931]
### Task description

The message and address builders have different methods to get a different result, for the message builder `finish()` and `prepare_transaction()` and for the address builder `finish()`, `get_all()`, `get_raw`, `get_all_raw()`
Somehow the different methods need to be made available in the message interface, one quick option would be to duplicate 
https://github.com/iotaledger/iota.rs/blob/7e3e97219d32d92b3ec0cd6163737945a033dc4c/src/message_interface/message_handler.rs#L78-L87 and only change `.finish()` and the response type
Another way would be to add something in the options to say what to expect and return an enum or maybe we could also align the response types (at least for the address builder)
For the address builder it's probably also enough if we can get the public and internal addresses as bech32 String, because they can be converted to the hex representation if needed

### Requirements

- [ ] Make it possible to generate public and internal addresses
- [ ] Make it possible to get the `PreparedTransactionData` and a sent `MessageDto`

### Acceptance criteria

N/A

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [ ] I have linked the correct milestone and/or project
